---
title: "Cover Letter"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

To the Editor:

Please find attached our revised paper. The paper was previously titled "A comparison of objective attributes and cyclists' perceptions along cycling routes in a Canadian developing cycling city", which has been revised to "Using environmental audits and photo-journeys to compare objective attributes and cyclists' perceptions along cycling routes" to reflect both the methodological and practical contributions of this work. We would like to thank the editor and two anonymous reviewers for their constructive comments and suggestions.

We believe that this paper makes the following contributions to the literature:

1.	The research reported here contributes to the literature on the topic of the relationship between the built environment and cycling for transportation in a developing cycling city where cycling levels are currently low but growing. Other recent papers have explored cycling for transportation in developing cycling cities (see Caufield, 2014; Clark et al., 2019; Félix et al., 2019; Mayers & Glover, 2019; Liu et al., 2020); to the best of our knowledge, the case of Hamilton, Ontario, Canada has not yet been reported. There is growing interest in studying these settings because they offer new insights for encouraging cycling for transport and opportunity to investigate cyclists' preferences, as well as how and if existing efforts to date have been successful in increasing cycling levels.

2. We employ a mixed methods approach to compare objectively measured attributes and cyclists' perceptions of the built environment along select cycling routes in Hamilton. The routes were selected based on the output of a model of cycling flows, which is described in another paper that has been submitted to *Transportation*. A novel feature of the analysis was the use of *CycleStreets* to infer and compare different routes between origins and destinations, and include the distance/time of different routes as measures of cost in the analysis. The model enabled us to identify cycling flows where there was more or less cycling than expected, which then presented opportunity to audit routes that were most poorly estimated to document their built environment. We hypothesized that discrepancies between the number of observed trips and the number of expected trips are due to the built environment, namely attributes along the quietest distance route that influence cycling but that we were not able to capture in the model. We conducted six environmental audits using the *Systematic Pedestrian and Cycling Environmental Scan*, and then recruited 14 people who regularly cycle in Hamilton to review photo journeys of the audited routes and explore their perceptions. Participants were also asked to compare different routes and select the one that they preferred. By drawing on quantitative and qualitative data, we gained a more holistic understanding of the influence of the built environment along cycling routes in Hamilton on cycling behaviours. The methods used in this study, particularly photo elicitation, may be of interest to transport planners and can be adopted in other developing cycling cities to study the objective and perceived attributes of cycling routes.

3. The analysis indicates that cycling routes in Hamilton have a mix of attributes that support and hinder cycling, as could be expected in a developing cycling city. Our findings with respect to cyclists' route preferences are congruent with the existing literature: they prefer routes that have dedicated cycling infrastructure, or residential streets with low volumes of traffic even if they lack infrastructure. They dislike routes with busy arterial roads or that lack cycling infrastructure. We also found that there is a threshold of unpleasantness that people who cycle are willing to tolerate along a route. This underscored that the fragmented nature of the cycling network in a developing cycling city can create barriers for accessing bikeable streets. We explore the policy implications of the current design of existing infrastructure in Hamilton, and offer recommendations for other developing cycling cities who might face similar challenges in adapting their carcentric cities to the bicycle or in designing infrastructure that supports cycling. Finally, a few studies have found a similarity in route preferences and barriers to cycling between cyclists and non-cyclists (see Clark et al., 2019; Félix et al., 2019; Winters et al., 2010) which also suggests that the perspectives of people who currently cycle can be informative about what might need to be improved to encourage more people to cycle. Our findings indicate that regular cyclists have both positive and negative experiences with infrastructure, and that their perceptions should be explored and leveraged to inform policies and interventions. 

We trust that you will find the suggestions from the reviewers helped to improve our manuscript, and we believe it is a stronger paper as a result.

Sincerely,

The Authors
